version: "3"

services:
  node:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: acrylicshrimp/rectchat
    environment:
      - NODE_ENV=production
    ports:
      - "8000:8000"
    command:
      - node src/main.js
    volumes:
      - /srv/chat:/srv/app/static
