version: '3'

services:
    node:
        build:
            context: .
            dockerfile: ./Dockerfile
        image: acrylicshrimp/rectchat:latest
        environment:
            - NODE_ENV=production
        ports:
            - '8000:8000'
